### ISSUE TITLE
500 error for /auth/callback/ request

### ISSUE THREAD

**Issue by biomassives** [hotosm/fmtm#131]
**Describe the bug**

this bug is indicative of a possible misconfiguration to open street map auth. 

**To Reproduce**

1. Go to '...' https://fmtm-api.hotosm.org/docs#/default/callback_auth_callback__get
2. Click on '....' execute
<span><span><h4>Server response</h4>

Code | Details
-- | --
500 Undocumented | Error: Internal Server Error

</span></span>

5. See error

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by biomassives** [comment]
curl -X 'GET' \\  
\>   '[https://fmtm-api.hotosm.org/auth/callback/](https://fmtm-api.hotosm.org/auth/callback/)' \\  
\>   -H 'accept: application/json'  
Traceback (most recent call last):  
  File "/home/appuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in \_\_call\_\_  
    await self.app(scope, receive, \_send)  
  File "/home/appuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in \_\_call\_\_  
    await self.app(scope, receive, send)  
  File "/home/appuser/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in \_\_call\_\_  
    raise exc  
  File "/home/appuser/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in \_\_call\_\_  
    await self.app(scope, receive, sender)  
  File "/home/appuser/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in \_\_call\_\_  
    raise e  
  File "/home/appuser/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in \_\_call\_\_  
    await self.app(scope, receive, send)  
  File "/home/appuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 680, in \_\_call\_\_  
    await route.handle(scope, receive, send)  
  File "/home/appuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle  
    await self.app(scope, receive, send)  
  File "/home/appuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app  
    response = await func(request)  
  File "/home/appuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app  
    raw\_response = await run\_endpoint\_function(  
  File "/home/appuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run\_endpoint\_function  
    return await run\_in\_threadpool(dependant.call, \*\*values)  
  File "/home/appuser/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run\_in\_threadpool  
    return await [anyio.to](http://anyio.to)\_thread.run\_sync(func, \*args)  
  File "/home/appuser/.local/lib/python3.9/site-packages/anyio/to\_thread.py", line 31, in run\_sync  
    return await get\_asynclib().run\_sync\_in\_worker\_thread(  
  File "/home/appuser/.local/lib/python3.9/site-packages/anyio/\_backends/\_asyncio.py", line 937, in run\_sync\_in\_worker\_thread  
    return await future  
  File "/home/appuser/.local/lib/python3.9/site-packages/anyio/\_backends/\_asyncio.py", line 867, in run  
    result = context.run(func, \*args)  
  File "/app/./backend/auth/routers.py", line 65, in callback  
    access\_token = osm\_auth.callback(str(request.url))  
  File "/home/appuser/.local/lib/python3.9/site-packages/osm\_login\_python/core.py", line 43, in callback  
    self.oauth.fetch\_token(  
  File "/home/appuser/.local/lib/python3.9/site-packages/requests\_oauthlib/oauth2\_session.py", line 244, in fetch\_token  
    self.\_client.parse\_request\_uri\_response(  
  File "/home/appuser/.local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/web\_application.py", line 220, in parse\_request\_uri\_response  
    response = parse\_authorization\_code\_response(uri, state=state)  
  File "/home/appuser/.local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 278, in parse\_authorization\_code\_response  
    raise MismatchingStateError()  
oauthlib.oauth2.rfc6749.errors.MismatchingStateError: (mismatching\_state) CSRF Warning! State not equal in request and response.
